import { Project, Experience } from './types';

export const projectsData: Project[] = [
  {
    id: 1,
    title: 'ChatPDF - AI Document Assistant',
    description: 'An interactive AI-powered application that allows users to upload PDF documents and extract summaries, ask contextual questions, or search terms using natural language processing.',
    techStack: ['React', 'Next.js', 'Tailwind CSS', 'OpenAI', 'Pinecone'],
    githubUrl: '',
    liveUrl: 'https://www.chatpdf.com/',
    category: 'Deep Learning',
    gradient: 'from-purple-600 via-pink-600 to-rose-600',
    imageUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&q=80&w=600',
    showGithub: false,
  },
  {
    id: 2,
    title: 'Supabase Open Database Console',
    description: 'A highly scalable database management console featuring real-time data listener grids, robust row-level security visualizers, and instant SQL query auto-complete.',
    techStack: ['React', 'TypeScript', 'Tailwind CSS', 'PostgreSQL', 'Go'],
    githubUrl: '',
    liveUrl: 'https://supabase.com/',
    category: 'Backend',
    gradient: 'from-cyan-500 via-teal-500 to-teal-600',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=600',
    showGithub: false,
  },
  {
    id: 3,
    title: 'v0 Generative UI Sandbox',
    description: 'A state-of-the-art developer platform that leverages generative AI models to convert natural language prompts into clean, interactive, and production-ready React component code.',
    techStack: ['Next.js', 'React', 'Generative AI', 'Vercel', 'Tailwind CSS'],
    githubUrl: '',
    liveUrl: 'https://v0.dev/',
    category: 'Frontend',
    gradient: 'from-violet-600 via-purple-600 to-indigo-600',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=600',
    showGithub: false,
  },
  {
    id: 4,
    title: 'Kapa.ai - SDK & API Copilot',
    description: 'An intelligent developer assistant that ingests developer documentation, GitHub repositories, and API endpoints to answer intricate integration questions with contextual code templates.',
    techStack: ['React', 'TypeScript', 'LangChain', 'OpenAI SDK', 'Python'],
    githubUrl: '',
    liveUrl: 'https://www.kapa.ai/',
    category: 'Full Stack',
    gradient: 'from-blue-600 via-indigo-600 to-indigo-700',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=600',
    showGithub: false,
  },
];

export const experienceData: Experience[] = [
  {
    id: 1,
    role: 'CTO & Co-Founder',
    company: 'Haxudio Digital Solutions',
    type: 'Full-time',
    period: 'Jan 2023 – Present',
    description: 'Leading the technical vision and architecture of a service-based digital agency. Managing a team of developers, overseeing project delivery, and driving innovation in web and mobile solutions for clients globally.',
    skills: ['Next.js', 'Node.js', 'Team Leadership', 'System Architecture', 'Client Relations'],
  },
  {
    id: 2,
    role: 'Freelance Full-Stack Developer',
    company: 'Self-Employed',
    type: 'Freelance',
    period: 'Jun 2022 – Dec 2022',
    description: 'Delivered 10+ custom web applications for international clients on platforms like Fiverr and Upwork. Specialized in MERN stack development, REST API design, and responsive UI implementation.',
    skills: ['React', 'Express.js', 'MongoDB', 'REST APIs', 'Tailwind CSS'],
  },
  {
    id: 3,
    role: 'Web Development Student',
    company: 'Saylani Mass IT Training (SMIT)',
    type: 'Training',
    period: 'Jan 2022 – Jun 2022',
    description: 'Completed an intensive full-stack web development bootcamp covering JavaScript, React, Node.js, and databases. Built multiple real-world projects under professional mentorship.',
    skills: ['JavaScript', 'React', 'Node.js', 'MongoDB', 'Git'],
  },
  {
    id: 4,
    role: 'Open Source Contributor',
    company: 'GitHub Community',
    type: 'Voluntary',
    period: 'Mar 2023 – Present',
    description: 'Actively contribute to open-source projects on GitHub, including bug fixes, feature additions, and documentation improvements across MERN stack repositories.',
    skills: ['Git', 'GitHub', 'Code Review', 'TypeScript'],
  },
];
